from jinja2 import Environment, FileSystemLoader
from logger import get_logger

log = get_logger()


def render_and_save_configs(interfaces, device_host, timestamp, execution_mode):
    """
    Renders each interface config through the Jinja2 template
    and saves the full output to configs/generated/ before deployment.

    Execution mode is stamped in the file header so every saved config
    is traceable to the run that produced it.

    Returns the path of the saved file, or None on failure.
    """
    log.info("Rendering configs from Jinja2 template...")

    try:
        env      = Environment(loader=FileSystemLoader("templates"))
        template = env.get_template("interface.j2")

        rendered_blocks = []

        for intf in interfaces:
            rendered = template.render(intf)
            rendered_blocks.append(rendered.strip())

        full_config = "\n!\n".join(rendered_blocks)

        config_file = (
            f"configs/generated/config_{device_host}_{timestamp}.txt"
        )

        with open(config_file, "w", encoding="utf-8") as f:
            f.write(f"! Generated by NetDevOps Framework\n")
            f.write(f"! Execution Mode : {execution_mode}\n")
            f.write(f"! Device         : {device_host}\n")
            f.write(f"! Timestamp      : {timestamp}\n")
            f.write(f"!\n")
            f.write(full_config)
            f.write(f"\n!")

        log.info(f"Rendered config saved — {config_file}")
        return config_file

    except Exception as e:
        log.error(f"Config rendering failed — {e}")
        return None