from netmiko import ConnectHandler
from jinja2 import Environment, FileSystemLoader
from datetime import datetime
import argparse
import json
import difflib
import os

from load_inventory import load_devices, load_interfaces
from logger import get_logger

# =========================
# LOGGER
# =========================
log = get_logger()

# =========================
# ARGUMENT PARSER (NEW IN V6)
# =========================
parser = argparse.ArgumentParser(
    description="NetDevOps Framework V6"
)

parser.add_argument(
    "--dry-run",
    action="store_true",
    help="Run validation only without pushing changes"
)

args = parser.parse_args()

# =========================
# EXECUTION MODE
# =========================
EXECUTION_MODE = "DRY-RUN" if args.dry_run else "LIVE"

# =========================
# CREATE PROJECT FOLDERS
# =========================
os.makedirs("backups", exist_ok=True)
os.makedirs("configs/generated", exist_ok=True)
os.makedirs("reports/json", exist_ok=True)
os.makedirs("reports/html", exist_ok=True)
os.makedirs("logs", exist_ok=True)

# =========================
# LOAD INVENTORY
# =========================
devices = load_devices()
interfaces = load_interfaces()

# =========================
# BUILD EXPECTED CONFIG
# =========================
def build_expected_lines(intf):

    lines = []

    lines.append(
        f"description {intf['description']}"
    )

    if intf.get("routed"):
        lines.append("no switchport")
        lines.append(
            f"ip address {intf['ip']} {intf['mask']}"
        )

    if not intf.get("enabled"):
        lines.append("shutdown")

    return lines

# =========================
# CONNECT
# =========================
def connect(device):

    log.info(f"Connecting to {device['host']}...")

    try:
        conn = ConnectHandler(**device)

        log.info(
            f"Connection established — {device['host']}"
        )

        return conn

    except Exception as e:

        log.error(
            f"Connection failed — {device['host']} — {e}"
        )

        raise

# =========================
# GET RUNNING CONFIG
# =========================
def get_running_config(conn):

    log.info("Collecting running config...")

    return conn.send_command(
        "show running-config"
    )

# =========================
# RENDER + SAVE CONFIGS
# =========================
def render_and_save_configs(
    interfaces,
    device_host,
    timestamp
):

    log.info(
        "Rendering configs from Jinja2 template..."
    )

    try:

        env = Environment(
            loader=FileSystemLoader("templates")
        )

        template = env.get_template(
            "interface.j2"
        )

        rendered_blocks = []

        for intf in interfaces:

            rendered = template.render(intf)

            rendered_blocks.append(
                rendered.strip()
            )

        full_config = "\n!\n".join(
            rendered_blocks
        )

        config_file = (
            "configs/generated/"
            f"config_{device_host}_{timestamp}.txt"
        )

        with open(
            config_file,
            "w",
            encoding="utf-8"
        ) as f:

            f.write(
                "! Generated by NetDevOps Framework V6\n"
            )

            f.write(
                f"! Execution Mode : {EXECUTION_MODE}\n"
            )

            f.write(
                f"! Device         : {device_host}\n"
            )

            f.write(
                f"! Timestamp      : {timestamp}\n"
            )

            f.write("!\n")

            f.write(full_config)

            f.write("\n!")

        log.info(
            f"Rendered config saved — {config_file}"
        )

        return config_file

    except Exception as e:

        log.error(
            f"Config rendering failed — {e}"
        )

        return None

# =========================
# EXTRACT INTERFACE BLOCK
# =========================
def extract_interface_block(
    running_config,
    interface_name
):

    lines = running_config.splitlines()

    block = []

    in_block = False

    for line in lines:

        if (
            line.strip().lower()
            ==
            f"interface {interface_name.lower()}"
        ):

            in_block = True
            continue

        if in_block:

            if (
                line.startswith("interface ")
                or line.strip() == "!"
            ):
                break

            if line.strip():
                block.append(line.strip())

    return block

# =========================
# DIFF ENGINE
# =========================
def diff_configs(
    interfaces,
    running_config
):

    diff_report = {}

    for intf in interfaces:

        name = intf["interface"]

        expected = build_expected_lines(
            intf
        )

        actual = extract_interface_block(
            running_config,
            name
        )

        missing = [
            line
            for line in expected
            if line not in actual
        ]

        diff = list(
            difflib.unified_diff(
                expected,
                actual,
                fromfile="desired",
                tofile="actual",
                lineterm=""
            )
        )

        diff_report[name] = {
            "expected": expected,
            "actual": actual,
            "missing": missing,
            "diff": diff
        }

    return diff_report

# =========================
# COMPLIANCE ENGINE
# =========================
def compliance_check(diff_report):

    results = {}

    for intf, data in diff_report.items():

        if not data["missing"]:
            results[intf] = "COMPLIANT"
        else:
            results[intf] = "DRIFT"

    return results

# =========================
# REMEDIATION ENGINE
# =========================
def remediate(
    conn,
    compliance,
    interfaces
):

    any_drift = any(
        status == "DRIFT"
        for status in compliance.values()
    )

    if not any_drift:

        log.info(
            "All interfaces COMPLIANT — no remediation needed"
        )

        return

    for intf in interfaces:

        name = intf["interface"]

        status = compliance.get(name)

        if status == "DRIFT":

            log.warning(
                f"Remediating {name}..."
            )

            try:

                cfg = [
                    f"interface {name}"
                ]

                cfg.append(
                    f"description {intf['description']}"
                )

                if intf.get("routed"):

                    cfg.append(
                        "no switchport"
                    )

                    cfg.append(
                        f"ip address "
                        f"{intf['ip']} "
                        f"{intf['mask']}"
                    )

                else:

                    cfg.append(
                        "switchport"
                    )

                if intf.get("enabled"):

                    cfg.append(
                        "no shutdown"
                    )

                else:

                    cfg.append(
                        "shutdown"
                    )

                conn.send_config_set(cfg)

                log.info(
                    f"Remediation successful — {name}"
                )

            except Exception as e:

                log.error(
                    f"Remediation failed — {name} — {e}"
                )

# =========================
# HTML REPORT
# =========================
def generate_html_report(
    compliance,
    diff_report,
    device_host,
    config_file,
    filename
):

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    html = f"""
    <html>
    <head>
        <title>NetDevOps Compliance Report</title>

        <style>

            body {{
                font-family: Arial;
                margin: 40px;
                background: #f9f9f9;
            }}

            h1 {{
                color: #333;
            }}

            h2 {{
                color: #555;
                font-size: 14px;
            }}

            .meta {{
                background: #eef;
                border: 1px solid #ccd;
                border-radius: 6px;
                padding: 12px;
                margin-bottom: 20px;
                font-size: 13px;
            }}

            .section {{
                background: white;
                border: 1px solid #ddd;
                border-radius: 6px;
                padding: 16px;
                margin-bottom: 20px;
            }}

            .compliant {{
                color: green;
            }}

            .drift {{
                color: red;
            }}

            pre {{
                background: #f4f4f4;
                padding: 10px;
                border-radius: 4px;
                font-size: 13px;
            }}

            .rem {{
                color: red;
            }}

        </style>

    </head>

    <body>

    <h1>
        NetDevOps Compliance Report
    </h1>

    <h2>
        Device: {device_host}
        &nbsp;|&nbsp;
        Generated: {timestamp}
    </h2>

    <div class='meta'>

        <b>Execution Mode:</b>
        &nbsp; {EXECUTION_MODE}

        <br><br>

        <b>Rendered Config Archive:</b>
        &nbsp; {config_file if config_file else "Not available"}

    </div>

    <hr>
    """

    for intf, status in compliance.items():

        css = (
            "compliant"
            if status == "COMPLIANT"
            else "drift"
        )

        data = diff_report[intf]

        html += (
            f"<div class='section'>"
        )

        html += (
            f"<h3 class='{css}'>"
            f"[{status}] {intf}"
            f"</h3>"
        )

        html += (
            "<b>Expected:</b><pre>"
        )

        for line in data["expected"]:
            html += line + "\n"

        html += "</pre>"

        html += (
            "<b>Actual:</b><pre>"
        )

        for line in data["actual"]:
            html += line + "\n"

        html += "</pre>"

        if data["missing"]:

            html += (
                "<b>Missing Lines:</b><pre>"
            )

            for line in data["missing"]:

                html += (
                    f"<span class='rem'>"
                    f"- {line}"
                    f"</span>\n"
                )

            html += "</pre>"

        html += "</div>"

    html += "</body></html>"

    with open(filename, "w") as f:
        f.write(html)

# =========================
# MAIN
# =========================
def main():

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    log.info("=" * 60)

    log.info(
        f"NetDevOps Framework V6 "
        f"— {EXECUTION_MODE} MODE"
    )

    log.info("=" * 60)

    for device in devices:

        log.info(
            f"Processing device: {device['host']}"
        )

        # -------------------------
        # CONNECT
        # -------------------------
        try:

            conn = connect(device)

        except Exception:

            log.error(
                f"Skipping {device['host']}"
            )

            continue

        # -------------------------
        # BACKUP
        # -------------------------
        try:

            actual = get_running_config(conn)

            backup_file = (
                "backups/"
                f"backup_{device['host']}_{timestamp}.txt"
            )

            with open(backup_file, "w") as f:
                f.write(actual)

            log.info(
                f"Backup saved — {backup_file}"
            )

        except Exception as e:

            log.error(
                f"Backup failed — {e}"
            )

            conn.disconnect()

            continue

        # -------------------------
        # RENDER CONFIGS
        # -------------------------
        config_file = render_and_save_configs(
            interfaces,
            device["host"],
            timestamp
        )

        # -------------------------
        # DIFF ENGINE
        # -------------------------
        log.info(
            "Running diff engine..."
        )

        diff_report = diff_configs(
            interfaces,
            actual
        )

        # -------------------------
        # COMPLIANCE
        # -------------------------
        log.info(
            "Running compliance check..."
        )

        compliance = compliance_check(
            diff_report
        )

        for intf, result in compliance.items():

            if result == "COMPLIANT":

                log.info(
                    f"[OK]    {intf} → {result}"
                )

            else:

                log.warning(
                    f"[DRIFT] {intf} → {result}"
                )

        # -------------------------
        # DRY RUN CHECK
        # -------------------------
        if args.dry_run:

            log.warning(
                "DRY-RUN MODE — remediation skipped"
            )

        else:

            log.info(
                "Running remediation engine..."
            )

            remediate(
                conn,
                compliance,
                interfaces
            )

        # -------------------------
        # REPORTS
        # -------------------------
        json_file = (
            f"reports/json/report_{timestamp}.json"
        )

        html_file = (
            f"reports/html/report_{timestamp}.html"
        )

        try:

            with open(json_file, "w") as f:

                json.dump(
                    {
                        "execution_mode":
                        EXECUTION_MODE,

                        "device":
                        device["host"],

                        "timestamp":
                        timestamp,

                        "config_file":
                        config_file,

                        "compliance":
                        compliance,

                        "diff": {
                            k: {
                                "expected":
                                v["expected"],

                                "actual":
                                v["actual"],

                                "missing":
                                v["missing"],

                                "diff":
                                v["diff"]
                            }
                            for k, v
                            in diff_report.items()
                        }
                    },
                    f,
                    indent=4
                )

            generate_html_report(
                compliance,
                diff_report,
                device["host"],
                config_file,
                html_file
            )

            log.info(
                f"JSON report saved — {json_file}"
            )

            log.info(
                f"HTML report saved — {html_file}"
            )

        except Exception as e:

            log.error(
                f"Report generation failed — {e}"
            )

        # -------------------------
        # DISCONNECT
        # -------------------------
        conn.disconnect()

        log.info(
            f"Disconnected from {device['host']}"
        )

    log.info("=" * 60)

    log.info(
        "NetDevOps Framework V6 — Execution Complete"
    )

    log.info("=" * 60)

# =========================
# RUN
# =========================
if __name__ == "__main__":
    main()